/* All orders placed by a specific customer */
SELECT concat(customers.first_name,' ',customers.last_name) AS Customer,
product_name,quantity
FROM order_details
JOIN orders ON orders.id = order_details.order_id
JOIN products ON order_details.product_id = products.id
JOIN customers ON customers.id = orders.customer_id
WHERE customers.first_name = 'Anna' AND customers.last_name = 'Bedecs';

/* All products that belong to a specific category */
SELECT DISTINCT category FROM products;
SELECT id, product_name, category, list_price
FROM products
WHERE category = 'Condiments';

 /* All employees along with their job titles */
 SELECT concat(first_name,' ',last_name) AS employee_name, job_title
 FROM employees;
 
 /* All orders shipped to a specific province */
 SELECT DISTINCT State_province FROM customers;
 SELECT concat(first_name,' ',last_name) AS customer_name,
 ship_state_province,product_name,quantity
 FROM customers
 JOIN orders ON customers.id = orders.customer_id
 JOIN order_details ON orders.id = order_details.order_id
 JOIN products ON order_details.product_id = products.id
 WHERE ship_state_province = 'NY' ;
 
/* All products with a price above a certain threshold */
SELECT id, product_name, list_price
FROM products
WHERE list_price > 30;

/* Total number of orders placed by each customer */
SELECT customer_id,COUNT(id) AS total_orders
FROM orders
GROUP BY customer_id;

/* Total revenue generated by each product */
SELECT product_name, SUM(order_details.quantity * unit_price) AS total_revenue 
FROM products
JOIN order_details ON products.id = order_details.product_id
GROUP BY product_name;

/* Average order value per customer */
SELECT o.customer_id,concat(first_name,' ',last_name) AS customer_name,
AVG(order_totals.order_total) AS avg_order_value
FROM orders o
JOIN (
    SELECT order_id, SUM(quantity * unit_price) AS order_total
    FROM order_details
    GROUP BY order_id
) AS order_totals ON o.id = order_totals.order_id
JOIN customers ON o.customer_id = customers.id
GROUP BY o.customer_id
ORDER BY o.customer_id;

/* Which categories have more than 10 products */
/* No category with more than 10 products */
SELECT category, COUNT(id) AS product_count
FROM products
GROUP BY category
ORDER BY product_count DESC;

/* Total sales per province */
SELECT ship_state_province,SUM(quantity * unit_price) as sales
FROM orders 
JOIN order_details ON orders.id = order_details.order_id
GROUP BY ship_state_province;

/* For each order, show customer name, employee who handled it, 
and shipping company */
SELECT 
    concat(c.first_name,' ', c.last_name) AS customer_name,
    concat(e.first_name,' ', e.last_name) AS employee_name,
    s.company AS shipping_company
FROM orders o
JOIN customers c ON o.customer_id = c.id
JOIN employees e ON o.employee_id = e.id
JOIN shippers s ON o.shipper_id = s.id;

/* List the top 10 products by total revenue, including category */
SELECT products.id, product_name, SUM(quantity * unit_price) AS total_revenue, category
FROM products
JOIN order_details ON products.id = order_details.product_id
GROUP BY products.id, product_name, category
ORDER BY total_revenue DESC
LIMIT 10;

/* Find all customers who have never placed an order */ 
SELECT customers.id, customers.first_name, customers.last_name
FROM customers
LEFT JOIN orders ON customers.id = orders.customer_id
WHERE orders.id IS NULL;

/*List employees and the total revenue they've generated through their orders*/
SELECT employees.id,concat(first_name,' ',last_name) AS employee_name,
SUM(quantity * unit_price) as revenue_generated
FROM employees
JOIN orders ON employees.id = orders.employee_id
JOIN order_details ON orders.id = order_details.order_id
GROUP BY id,employee_name
ORDER BY id;

/* Rank customers by total spend */
SELECT customers.id,concat(first_name,' ',last_name) AS customer_name,
SUM(quantity * unit_price) as total_spend,
RANK() OVER (ORDER BY SUM(quantity * unit_price) DESC) AS spend_rank
FROM customers
JOIN  orders ON customers.id = orders.customer_id
JOIN order_details ON orders.id = order_details.order_id
GROUP BY customers.id,customer_name;

/* Running total of spend per customer over time */
SELECT customers.id,orders.id,order_date,
	SUM(quantity * unit_price) AS order_total,
	SUM(SUM(quantity * unit_price))
OVER(PARTITION BY customers.id ORDER BY order_date)
AS running_total
FROM customers
JOIN orders ON customers.id = orders.customer_id
JOIN order_details ON orders.id = order_details.order_id
GROUP BY customers.id,orders.id,order_date
ORDER BY customers.id,order_date;

/* Each customer's most recent order */
SELECT * FROM 
	(SELECT * ,ROW_NUMBER() OVER 
    (PARTITION BY customer_id ORDER BY order_date DESC) AS rn
	FROM orders) t
WHERE rn = 1

/* Month-over-month revenue change */
WITH monthly AS (
SELECT DATE_FORMAT(order_date,'%Y-%m') AS month,
		SUM(quantity * unit_price) AS revenue
FROM orders
JOIN order_details ON orders.id = order_details.order_id
GROUP BY DATE_FORMAT (order_date,'%Y-%m')
)
SELECT month, revenue,
	LAG(revenue) OVER (ORDER BY month) AS prev_month_revenue,
    revenue - LAG(revenue) OVER (ORDER BY month) AS changes
FROM monthly
ORDER BY month;

/* Top 3 best-selling products per category */
WITH product_sales AS (
	SELECT products.id,product_name,category,
		SUM(quantity * unit_price) AS revenue
	FROM products
    JOIN order_details ON products.id = order_details.product_id
    GROUP BY products.id, product_name, products.category
),
ranked AS (
	SELECT *,RANK() OVER (PARTITION BY category ORDER BY revenue DESC) AS rnk 
    FROM product_sales
)
SELECT * FROM ranked WHERE rnk <= 3;

/* Customers spending above the average */
WITH customer_spend AS (
    SELECT c.id, c.first_name, c.last_name,
           SUM(od.quantity * od.unit_price) AS total_spend
    FROM customers c
    JOIN orders o ON c.id = o.customer_id
    JOIN order_details od ON o.id = od.order_id
    GROUP BY c.id, c.first_name, c.last_name
)
SELECT * FROM customer_spend
WHERE total_spend > (SELECT AVG(total_spend) FROM customer_spend);